com:
  sparta:
    sample:
      #Generate your key at: https://www.zipcodeapi.com/
      api-key: <YOUR KEY HERE> 
      
      two-way-ssl:
        enabled: true
        enable-hostname-verifier: true
        #TrustStore to validate server certificate
        trustStore: 
          file: 
          pass: 
          type: JKS
        #For client Cert on Two-way-ssl
        keyStore:  
          file:
          pass: 
          type: JKS

